# Generated by Django 3.2.13 on 2022-05-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Product',
        ),
    ]
